<div class="navbar-fixed">
<nav>
    <div class="nav-wrapper #2196f3 blue">
    <a href="#" class="brand-logo ">ZYANG</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class="nav"><a href="home.php">Home</a></li>
          <li class="nav"><a href="pf.php">Portfolio</a></li>
          <li class="nav"><a href="contact-form.php">Contact Form</a></li>
      </ul>

      <ul class="side-nav" id="mobile-demo">
          <li class="nav"><a href="home.php">Home</a></li>
          <li class="nav"><a href="pf.php">Portfolio</a></li>
          <li class="nav"><a href="contact-form.php">Contact Form</a></li>
      </ul>

    </div>
  </nav>
</div>

      
