
<nav class="nav #2196f3 blue">
    <div class="nav-wrapper ">
    <a href="index.php" class="brand-logo ">ZYANG</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
          <li><a href="index.php">Home</a></li>
          <li><a href="pf.php">Portfolio</a></li>
          <li><a href="html-form.php">Contact Form</a></li>
      </ul>

      <ul class="side-nav" id="mobile-demo">
          <li><a href="index.php">Home</a></li>
          <li><a href="pf.php">Portfolio</a></li>
          <li><a href="html-form.php">Contact Form</a></li>
      </ul>

    </div>
  </nav>

      
